### ISSUE TITLE
wiring-0.2.0.0 does not compile with GHC 7.8.4

### ISSUE THREAD

**Issue by peti** [seanparsons/wiring#1]
A complete build log is available at http://hydra.cryp.to/build/559719/nixlog/2/raw.

**Comment by seanparsons** [comment]
Travis and my own local builds say otherwise: https://travis-ci.org/seanparsons/wiring/jobs/50833722

**Comment by seanparsons** [comment]
Weird, I've got something similar myself...

**Comment by seanparsons** [comment]
Odd, it would appear that source code isn't being pulled through by the sdist command...

**Comment by seanparsons** [comment]
Fixed it by adding the other-modules setting to include those files. :(

Le sigh.
